language: python
cache: pip
python:
- '3.6'
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then export CXX=g++-4.8; fi
  - wget https://github.com/rdfhdt/hdt-cpp/archive/v1.3.3.zip
  - unzip v1.3.3.zip
install:
  - pip install -r requirements.txt
  - pip install pytest sphinx sphinx_rtd_theme
  - python setup.py install
script:
  - pytest
before_deploy:
  - rm -rf build/
  - cd docs && make html
deploy:
- provider: pypi
  skip_cleanup: true
  user: callidon
  password: $PYPI_PASSWD
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES
  keep_history: true
  local_dir: docs/build/html
  on:
    branch: master
